#!/usr/bin/env bash
# =============================================================================
#  deployments-report.sh — generate docs/src/deployments.md from config/.
#
#  Reads config/deployments/<alias>.json + config/chains/<alias>.json and emits a
#  per-network table of deployed addresses plus the config that produced them
#  (chainId, selector, RMN, versionTag, resolver salt).
#
#  Also asserts the cross-chain invariant while it is here: the resolver must be at
#  the SAME address on every chain. A divergence is flagged in the output and sets
#  a non-zero exit, so this doubles as a CI check.
#
#  Explorer links come from the optional `explorerUrl` field in the chain config.
#
#  Usage: script/governance/deployments-report.sh [--check]
#           (no args)  write docs/src/deployments.md
#           --check    print to stdout, write nothing; exit 1 if the file is stale
#
#  Exit: 0 OK | 1 resolver divergence or (with --check) stale output | 2 MISSING_TOOL
# =============================================================================
set -uo pipefail

command -v jq > /dev/null 2>&1 || {
    echo "[deployments-report] MISSING_TOOL: jq not found on PATH" >&2
    exit 2
}

cd "$(dirname "$0")/../.." || exit 2
DEPLOYMENTS_DIR="config/deployments"
CHAINS_DIR="config/chains"
OUT="docs/src/deployments.md"
MODE="${1:-write}"

# Real per-deployment records only: templates and examples carry no usable address.
aliases() {
    for f in "$DEPLOYMENTS_DIR"/*.json; do
        [ -e "$f" ] || continue
        case "$(basename "$f")" in _template.json | *.example.json) continue ;; esac
        n="$(basename "$f" .json)"
        # A deployment record is only meaningful alongside its chain config.
        [ -f "$CHAINS_DIR/$n.json" ] && echo "$n"
    done
}

# link <alias> <address> -> markdown link if the chain declares an explorerUrl, else code
link() {
    local base
    base="$(jq -r '.explorerUrl // empty' "$CHAINS_DIR/$1.json")"
    if [ -n "$base" ] && [ "$2" != "0x0000000000000000000000000000000000000000" ]; then
        printf '[`%s`](%s/address/%s)' "$2" "${base%/}" "$2"
    else
        printf '`%s`' "$2"
    fi
}

render() {
    local names resolvers=""
    names="$(aliases)"

    echo "# Deployed addresses"
    echo
    if [ -z "$names" ]; then
        echo "No deployments recorded yet. Deploy scripts write \`config/deployments/<alias>.json\`;"
        echo "re-run \`script/governance/deployments-report.sh\` to regenerate this page."
        return 0
    fi

    echo "> Generated by \`script/governance/deployments-report.sh\` from \`config/\`."
    echo "> Do not edit by hand — re-run \`script/governance/deployments-report.sh\` after a deploy."
    echo

    echo "## Contracts"
    echo
    echo "| Chain | Factory | Resolver | Verifier |"
    echo "|---|---|---|---|"
    for n in $names; do
        f="$(jq -r '.factory'  "$DEPLOYMENTS_DIR/$n.json")"
        r="$(jq -r '.resolver' "$DEPLOYMENTS_DIR/$n.json")"
        v="$(jq -r '.verifier' "$DEPLOYMENTS_DIR/$n.json")"
        resolvers="$resolvers$r"$'\n'
        printf '| `%s` | %s | %s | %s |\n' "$n" "$(link "$n" "$f")" "$(link "$n" "$r")" "$(link "$n" "$v")"
    done
    echo

    echo "## Deploy-time inputs"
    echo
    echo "\`rmn\` and \`versionTag\` are CommitteeVerifier constructor arguments, both immutable"
    echo "after deployment. \`resolverSalt\` is the CREATE2 salt that fixes the resolver's address"
    echo "(the resolver itself takes no constructor arguments)."
    echo
    echo "| Chain | Chain ID | Selector | Verifier: rmn | Verifier: versionTag | Resolver: CREATE2 salt |"
    echo "|---|---:|---|---|---|---|"
    for n in $names; do
        jq -r --arg n "$n" '
          "| `\($n)` | \(.chainId) | `\(.chainSelector)` | `\(.rmn)` | `\(.versionTag)` | `\(.resolverSalt)` |"
        ' "$CHAINS_DIR/$n.json"
    done
    echo

    # The invariant: one resolver address everywhere. Equal salts are necessary but not
    # sufficient — the factory address and initcode must match too — so compare the
    # recorded addresses themselves.
    local distinct
    distinct="$(printf '%s' "$resolvers" | sed '/^$/d' | sort -u | wc -l | tr -d ' ')"
    echo "## Resolver address parity"
    echo
    if [ "$distinct" = "1" ]; then
        echo "✅ The resolver is at the same address on every recorded chain:"
        echo
        printf '    %s\n' "$(printf '%s' "$resolvers" | sed '/^$/d' | sort -u)"
    else
        echo "❌ **The resolver address DIVERGES across chains.** Integrators hardcode one"
        echo "resolver address, so this must be fixed before the lanes are usable. Distinct"
        echo "addresses recorded:"
        echo
        printf '%s' "$resolvers" | sed '/^$/d' | sort -u | sed 's/^/    /'
    fi
    return 0
}

body="$(render)"
status=0
printf '%s' "$body" | grep -q "DIVERGES" && status=1

if [ "$MODE" = "--check" ]; then
    printf '%s\n' "$body"
    if [ -f "$OUT" ] && ! diff -q <(printf '%s\n' "$body") "$OUT" > /dev/null 2>&1; then
        echo "[deployments-report] STALE: $OUT does not match config/; re-run script/governance/deployments-report.sh" >&2
        exit 1
    fi
    exit $status
fi

mkdir -p "$(dirname "$OUT")"
printf '%s\n' "$body" > "$OUT"
echo "[deployments-report] wrote $OUT"
exit $status
